<a href="https://colab.research.google.com/github/Bhumik1277/B_1277/blob/main/basicsofnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])

In [3]:
print("1D Array:")
print("Shape:", arr_1d.shape)
print("Size:", arr_1d.size)
print("Dimension:", arr_1d.ndim)
print("Length:", len(arr_1d))
print()

1D Array:
Shape: (5,)
Size: 5
Dimension: 1
Length: 5



In [4]:
print("2D Array:")
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Dimension:", arr_2d.ndim)
print("Length:", len(arr_2d))
print()

2D Array:
Shape: (3, 3)
Size: 9
Dimension: 2
Length: 3



In [5]:
print("3D Array:")
print("Shape:", arr_3d.shape)
print("Size:", arr_3d.size)
print("Dimension:", arr_3d.ndim)
print("Length:", len(arr_3d))
print()

3D Array:
Shape: (2, 2, 3)
Size: 12
Dimension: 3
Length: 2



In [6]:
print("Examples of array creation functions:")
print("np.arange(5):", np.arange(5))
print("np.random.randint(1, 10, size=(2, 3)):")
print(np.random.randint(1, 10, size=(2, 3)))
print("np.random.rand(2, 3):")
print(np.random.rand(2, 3))
print("np.linspace(0, 10, 5):", np.linspace(0, 10, 5))
print("np.ones((2, 3)):")
print(np.ones((2, 3)))
print("np.zeros((2, 3)):")
print(np.zeros((2, 3)))
print("np.diag([1, 2, 3]):")
print(np.diag([1, 2, 3]))

Examples of array creation functions:
np.arange(5): [0 1 2 3 4]
np.random.randint(1, 10, size=(2, 3)):
[[8 2 9]
 [5 5 1]]
np.random.rand(2, 3):
[[0.09618998 0.1100229  0.56857262]
 [0.3737176  0.94080072 0.27423902]]
np.linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
np.ones((2, 3)):
[[1. 1. 1.]
 [1. 1. 1.]]
np.zeros((2, 3)):
[[0. 0. 0.]
 [0. 0. 0.]]
np.diag([1, 2, 3]):
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
print("\nExamples of aggregation functions:")
print("Sum of arr_2d:", np.sum(arr_2d))
print("Min of arr_1d:", np.min(arr_1d))
print("Max of arr_3d:", np.max(arr_3d))
print("Mean of arr_2d:", np.mean(arr_2d))



Examples of aggregation functions:
Sum of arr_2d: 45
Min of arr_1d: 1
Max of arr_3d: 12
Mean of arr_2d: 5.0
